# .github/workflows/flake8.yml

name: flake8

on: [push, pull_request]

jobs:
    black:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.10

            - name: Install dependencies with pip
              run: pip install flake8

            - name: Run flake8 check
              run: flake8
              
