# .github/workflows/linters.yml

name: linters

on: [push, pull_request]

jobs:
    linters:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.10.17

            - name: Install dependencies with pip
              run: pip install black isort flake8 mypy

            - name: Run black check
              run: black --check hw-007/.

            - name: Run isort check
              run: isort hw-007/. --check

            - name: Run flake8 check
              run: flake8 --max-line-length 88 hw-007/.

            - name: Run mypy
              run: mypy hw-007/. --check
