# .github/workflows/linters.yml

name: linters

on: [push, pull_request]

jobs:
    linters:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.10.17

            - name: Install dependencies with pip
              run: pip install black isort flake8 mypy

            - name: Run black check
              run: black --check .

            - name: Run isort check
              run: isort . --check

            - name: Run flake8 check
              run: flake8

            - name: Run mypy
              run: mypy . --check
